CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME CHAR(25) NOT NULL,
    LAST_NAME CHAR(25),
    SALARY INT CHECK (SALARY BETWEEN 10000 AND 25000),
    JOINING_DATE DATETIME, DEPARTMENT CHAR(25)
     CHECK (DEPARTMENT IN ('HR', 'Sales', 'Accts', 'IT')));
INSERT INTO Worker VALUES
(1, 'Pallavi', 'Panjla', 20000, '2016-06-11 00:00:00', 'HR'),
(2, 'Payal', 'Bhalla', 15000, '2017-08-20 00:00:00', 'Sales'),
(3, 'Aman', 'Bhalla', 25000, '2018-01-15 00:00:00', 'IT');

-- Q-1
SELECT FIRST_NAME AS WORKER_NAME FROM Worker;

-- Q-2
SELECT UPPER(FIRST_NAME) FROM Worker;

-- Q-3
SELECT DISTINCT DEPARTMENT FROM Worker;

-- Q-4
SELECT SUBSTRING(FIRST_NAME,1,3) FROM Worker;

-- Q-5
SELECT INSTR(FIRST_NAME,'a') FROM Worker WHERE FIRST_NAME='Amitabh';

-- Q-6
SELECT RTRIM(FIRST_NAME) FROM Worker;

-- Q-7
SELECT LTRIM(DEPARTMENT) FROM Worker;

-- Q-8
SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) FROM Worker;

-- Q-9
SELECT REPLACE(FIRST_NAME,'a','A') FROM Worker;

-- Q-10
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS COMPLETE_NAME FROM Worker;

-- Q-11
SELECT * FROM Worker ORDER BY FIRST_NAME ASC;

-- Q-12
SELECT * FROM Worker ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

-- Q-13
SELECT * FROM Worker WHERE FIRST_NAME IN ('Vipul','Satish');

-- Q-14
SELECT * FROM Worker WHERE FIRST_NAME NOT IN ('Vipul','Satish');

-- Q-15
SELECT * FROM Worker WHERE DEPARTMENT='Admin';

-- Q-16
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a%';

-- Q-17
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%a';

-- Q-18
SELECT * FROM Worker WHERE FIRST_NAME LIKE '_____h';

-- Q-19
SELECT * FROM Worker WHERE SALARY BETWEEN 100000 AND 500000;

-- Q-20
SELECT * FROM Worker WHERE YEAR(JOINING_DATE)=2014 AND MONTH(JOINING_DATE)=2;

-- Q-21
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM Worker WHERE DEPARTMENT='Admin';